### ISSUE TITLE
Run only changed models on PR if the `modeldb-run.yaml` file has changed

### ISSUE THREAD

**Issue by JCGoran** [neuronsimulator/nrn-modeldb-ci#104]
It would be extremely useful if, when opening a PR that only affects the `modeldb-run.yaml` file, the CI would run `runmodels` for either:

- only those models
- those models + all of the ones that already run on a PR

Rationale: currently, to figure out whether a fix for a model works, it requires us to manually run the GH action, which can be error-prone and is very tedious.
Comparing with the parent commit we can figure out the difference, and then the `modeldb-run.yaml` file could be parsed using something like `pyyaml` to figure out which models that difference has an impact on, which could be fed directly to `runmodels`.

**Comment by alexsavulescu** [comment]
You can specify MODELS_TO_RUN in the PR description: https://github.com/neuronsimulator/nrn-modeldb-ci/blob/master/.github/workflows/nrn-modeldb-ci.yaml#L117

**Comment by JCGoran** [comment]
Oh neat! Would be great if this was document somewhere other than the CI file itself though.
