### ISSUE TITLE
Build only (with no run) for Windows debugging.

### ISSUE THREAD

**Issue by nrnhines** [neuronsimulator/nrn-modeldb-ci#31]
I'm playing with the additional option for runmodels
```
+        --norun                 Compile and link. Success if nrnivmodl succeeds. (Useful for Windows when debugging incomplete g++ toolchain in installer.)
```
and am at the point where it seemed simplest to force every model to effectively have the yaml property ```run: null```.
I tried:
```
 class ModelRun(dict):
-    def __init__(self, model, working_dir, clean=False):
+    def __init__(self, model, working_dir, clean=False, norun=False):
```
to merely
```
-        self._fetch_model()
+        if not norun:
+            self._fetch_model()
```
but I guess ```_fetch_model()``` is getting more than just ```run```.
I'm wondering if someone can short circuit my guesswork by suggesting how to effectively replace the ```run``` after return from ```_fetch_model()```.

**Comment by olupton** [comment]
@alexsavulescu may have a better idea, but my guess would be that one could add
```python
if norun:
  self["run"] = None
```
after https://github.com/neuronsimulator/nrn-modeldb-ci/blob/f0fae7dcaca75db46024db45c301658a998f64ce/modeldb/modelrun.py#L49
🤔
