### ISSUE TITLE
Make sure GH and ModelDB are in sync (same content)

### ISSUE THREAD

**Issue by alexsavulescu** [neuronsimulator/nrn-modeldb-ci#71]
Out of Sync
===========
- [x] [126637](https://github.com/ModelDBRepository/126637) -> GH has newer version
- [x] [139653](https://github.com/ModelDBRepository/139653) -> GH has newer version
- [x] [246546](https://github.com/ModelDBRepository/246546) -> different content (keep ModelDB content) -> https://github.com/ModelDBRepository/246546/pull/1
- [x] [256311](https://github.com/ModelDBRepository/256311) -> ModelDB has newer version
- [x] [260971](https://github.com/ModelDBRepository/260971) -> different content (not sure which is appropriate) (fixed, see https://github.com/ModelDBRepository/260971/commit/2bbd294c4c7e96ae8fcc45fbd2c6229ad4011b3c)
- [x] [265584](https://github.com/ModelDBRepository/265584) -> GH has modern MOD updates, ModelDB has changes not retrofitted to GH -> https://github.com/ModelDBRepository/265584/pull/3 (fixed, see https://github.com/ModelDBRepository/265584/pull/3#issuecomment-1900346604)
- [x] [3808  ](https://github.com/ModelDBRepository/3808  ) -> GH has newer version
- [x] 267666 does not exist on GitHub
- [x] 267355 does not exist on GitHub

**Comment by RuiLi7222** [comment]
The models: 126637, 139653, 256311, 3808, and 266774 are solved. 
Models 246546, 260971, and 265584 still need further attention.

**Comment by olupton** [comment]
Model 267666 (new?) is missing from GitHub.

**Comment by olupton** [comment]
Model 267355 is also missing from GitHub.

**Comment by JCGoran** [comment]
Has this been resolved? I tried locally comparing all of the models from MODELDB with the ones from GH, and have found no differences between the two (modulo some unnecessary files/directories like `__MACOSX`, `.DS_Store`, `__pycache__`, etc.), nor any missing models.
For reference, I used this Bash script for downloading and comparing the files: https://gist.github.com/JCGoran/8e12f8a1aac70203c1f4e8a56171f088

**Comment by pramodk** [comment]
@JCGoran - if the two "unchecked" versions are now synced / same then it's OK to close this ticket. I added you to the @modeldb slack channel on NEURON-Dev where you can see related discussion / post additional questions.

**Comment by ramcdougal** [comment]
All ModelDB entries (not just NEURON models) should be in GitHub... Although having said this, I wonder if this is true for alternate model entries

**Comment by JCGoran** [comment]
@ramcdougal  I've made some ad-hoc Bash scripts which can be used to clean up the models on MODELDB (can probably be used on the GH ones as well, though I haven't tried it) in case it's of use: https://gist.github.com/JCGoran/c179761e47eee831134fa74f8b304061
