### ISSUE TITLE
MDB_MODEL_DOWNLOAD_URL needs to be updated

### ISSUE THREAD

**Issue by ramcdougal** [neuronsimulator/nrn-modeldb-ci#82]
In [modeldb/modeldb.py](https://github.com/neuronsimulator/nrn-modeldb-ci/tree/master/modeldb/modeldb.py), `MDB_MODEL_DOWNLOAD_URL` is set to pull from the Yale site. This link will become inoperative at somepoint in June. 

Instead of pulling all the data and metadata about a model to get the file contents, going forward `download_model` can get the file contents direclty via links of the form `https://modeldb.science/eavBinDown?o={model_id}`

**Comment by alexsavulescu** [comment]
The idea is to use GitHub to download models: https://github.com/neuronsimulator/nrn-modeldb-ci/pull/72

**Comment by alexsavulescu** [comment]
The idea is to use GitHub to download models: https://github.com/neuronsimulator/nrn-modeldb-ci/pull/72

**Comment by alexsavulescu** [comment]
However we still have https://github.com/neuronsimulator/nrn-modeldb-ci/issues/71

**Comment by olupton** [comment]
To avoid the very-high-latency cache setup we have at the moment, we need a way of efficiently getting the list of models to be tested **and some kind of last-updated timestamp or commit ID**. I believe this is well within the limits of the GitHub API.

**Comment by olupton** [comment]
Based on https://modeldb.science/api it looks like the results of https://modeldb.science/api/v1/models/id?modeling_application=NEURON and https://modeldb.science/api/v1/models/ver_date?modeling_application=NEURON could be zipped together to get a list of (id, date) pairs.

It seems "reasonable" to assume that these two queries will return results sorted by some common key, so it is safe to zip them together, but I don't see it documented that this is the case. Can you confirm @ramcdougal?

**Comment by ramcdougal** [comment]
Yes, the two queries are paired, and the API documentation on [ModelDB.science](https://modeldb.science) has been updated to reflect this.
