### ISSUE TITLE
CI: more robust GitHub actions caching

### ISSUE THREAD

**Issue by alexsavulescu** [neuronsimulator/nrn-modeldb-ci#9]
Currently we only rely on a simple keyword + date for caching. 
The idea is to somehow make use of ModelDB API so that we know when to retrieve (updated or new) models? Otherwise add a manual trigger?

**Comment by olupton** [comment]
Based on https://neuron.yale.edu/ftp/neuron/2019northwestern/python-2019-10-18.html it may be possible to use queries like https://senselab.med.yale.edu/_site/webapi/object.json/12631?woatts=23,24,25,26,27,28,112,113,114,155,249,299,471,488,502,582 to get the last-modified date of a model without downloading its content. It's not immediately clear how to query many models at once.

**Comment by alexsavulescu** [comment]
Ideally we'd get a unique API call with latest update times (like we have for getting all NEURON accession numbers https://github.com/neuronsimulator/nrn-modeldb-ci/blob/master/modeldb/config.py#L6 )  but I remember I couldn't find any.
